### ISSUE TITLE
30 chars limit

### ISSUE THREAD

**Issue by aritra1911** [CodeOn-ArK/RawTerm_CPP#16]
https://github.com/CodeOn-ArK/RawTerm_CPP/blob/77e53b0f2f9d1d647353676f6f004c447a22002c/menu.cpp#L124

The issue is that when you surpass this limit, the situation looks similar to the ^D hell as being discussed in issue #7.
Either extend the limit or use `std::string` since this is `C++` and not `C`.

**Comment by CodeOn-ArK** [comment]
issue will be scrutinized soon with care && caution

**Comment by CodeOn-ArK** [comment]
Issue fixed in latest commit; check test branch
