### ISSUE TITLE
Menu display Issue 

### ISSUE THREAD

**Issue by CodeOn-ArK** [CodeOn-ArK/RawTerm_CPP#42]
Issue still persists
![Screenshot_4](https://user-images.githubusercontent.com/70703857/114220490-b3bcdb80-9989-11eb-95d4-8d85a170b0ce.png)

**Comment by aritra1911** [comment]
Tell me the exacts steps of how to reproduce it?

**Comment by CodeOn-ArK** [comment]
Just git pull window_integration branch and make

**Comment by CodeOn-ArK** [comment]
Happy ending
