### ISSUE TITLE
markdown_issue

### ISSUE THREAD

**Issue by CodeOn-ArK** [CodeOn-ArK/RawTerm_CPP#8]
Please look into markdown_colour @class colour;
The obj hasa been made global still it can't remember any change made to that variable.
The obj has been externed to every file; with no result. @aritra1911

**Comment by aritra1911** [comment]
Please elaborate. I'm not finding it externed to any file as of right now and of course referring to the `test` branch.

**Comment by aritra1911** [comment]
Also if you know C++, you wouldn't have done this, also how is it compiling?
https://github.com/CodeOn-ArK/RawTerm_CPP/blob/6009c672db193dadea3fb476ff1de1232fb3bacb/Final_Project.cpp#L52

You cannot initialize data members inside class definition. You must initialize them during instantiation, i.e. in the constructor of the class.

**Comment by CodeOn-ArK** [comment]
all i know is .... it compiles successfully

**Comment by CodeOn-ArK** [comment]
leave this issue, u have bigger thnigs to solve
