### ISSUE TITLE
extern class object

### ISSUE THREAD

**Issue by CodeOn-ArK** [CodeOn-ArK/RawTerm_CPP#9]
the ```class class_mem``` has been defined within Final_Project.cpp, which needs to be externed to every other file. See if u can do and compile it successfully. @aritra1911

**Comment by CodeOn-ArK** [comment]
create object of class_mem and try to extern it

**Comment by aritra1911** [comment]
That's a simple solution, pull that out into it's own file, add include guards and then include that into every file you need it. Since it's just a class and not an object, that's the easy fix.

**Comment by aritra1911** [comment]
Extern is evaluated during linking btw, if you just want a global object, just instantiate it globally and the way you're doing it, just `#include` that file into every source file you need. That object exists throughout and hence done.

Also in these cases, think like declaring static member variables, so an instance isn't even necessary to make.

**Comment by CodeOn-ArK** [comment]
send me a PR

**Comment by CodeOn-ArK** [comment]
Done
